####################################################
#                                                  #
#               HA 2 General Config                #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customization

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_path
  ssl_key: !secret ssl_key
  base_url: !secret http_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

####################################################
#                                                  #
#               Components                         #
#                                                  #
####################################################

alarm_control_panel:
  platform: manual
  name: Alarm
  pending_time: 0
  trigger_time: 600
  disarm_after_trigger: false

binary_sensor:
  - platform: workday
    country: US
    state: IL
    
camera:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=LOT&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24691024&lat=0&lon=0&label=you
    name: weather_radar

climate:
  - platform: nest

device_tracker:
  - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts: 192.168.0.1-80
    track_new_devices: yes
    home_interval: 10
  - platform: owntracks
    max_gps_accuracy: 100
  - platform: ping
    hosts:
      billsphone: 192.168.0.40 
  - platform: mqtt
    devices:
      bills_6p: /zanzito/bills_phone/location/
      ginas_s6: /zanzito/ginas_phone/location/

ifttt:
  key: !secret ifttt_secret

media_player:
  - platform: cast
    host: 192.168.0.31
  - platform: webostv
    host: 192.168.0.36
    mac: A0-6F-AA-38-FE-1A
    name: Living Room TV
    customize:
      sources:
        - livetv
        - youtube
        - netflix
  - platform: plex
  - platform: sonos
  - platform: spotify
    client_id: a2e5eaeea9384512838c68cdac474697
    client_secret: c62ab709bcd8444ca0430e75125961d5

mqtt:
  broker: griffithshome.duckdns.org
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  binary_sensors:
    monitored_conditions:
      - 'online'
      - 'fan'
      - 'is_using_emergency_heat'
      - 'is_locked'
      - 'has_leaf'

notify:
  - platform: html5
    name: HTML5
    gcm_api_key: !secret html5_server_key
    gcm_sender_id: !secret html5_sender_id
  - platform: webostv
    host: 192.168.0.36
    name: Living Room TV


# Weather Prediction
sensor:
  - platform: darksky
    api_key: !secret dark_sky_api
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
  - platform: template
    sensors:
      chromecast:
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
  - platform: moon
  - platform: mqtt
    name: "Bills 6P Battery"
    state_topic: "zanzito/bills_phone/battery_level"
    qos: 0
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Ginas S6 Battery"
    state_topic: "zanzito/ginas_phone/battery_level"
    qos: 0
    unit_of_measurement: "%"
  - platform: nest
    monitored_conditions:
      - temperature
      - target
      - humidity
      - operation_mode
      - hvac_state
      - battery_level
      - co_status
      - smoke_status
      - weather_temperature
      - weather_humidity
      - weather_condition
      - wind_speed
      - wind_direction
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: command_line
    name: SSL Cert Expiry
    unit_of_measurement: days
    scan_interval: 86400
    command: !secret ssl_cert_expiry
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: last_boot
  - platform: time_date
    display_options:
      - "date_time"
  - platform: yr
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
  - platform: fedex
    username: !secret fedex_username
    password: !secret fedex_password
#  - platform: usps
#    username: !secret usps_username
#    password: !secret usps_password
  - platform: google_travel_time
    name: Billy Phone To Home
    api_key: AIzaSyAScHvjrbjWXIXBKkwT8Q4dyeD5MnJpirI
    origin: device_tracker.bills_phone_bills_phone
    destination: zone.home
  - platform: google_travel_time
    name: Billy Phone To Work
    api_key: AIzaSyAScHvjrbjWXIXBKkwT8Q4dyeD5MnJpirI
    origin: device_tracker.bills_phone_bills_phone
    destination: zone.bill_work_mtl
  - platform: google_travel_time
    name: Gina Phone To Home
    api_key: AIzaSyAScHvjrbjWXIXBKkwT8Q4dyeD5MnJpirI
    origin: device_tracker.ginas_phone_ginas_phone
    destination: zone.home
  - platform: google_travel_time
    name: Gina Phone To Work
    api_key: AIzaSyAScHvjrbjWXIXBKkwT8Q4dyeD5MnJpirI
    origin: device_tracker.ginas_phone_ginas_phone
    destination: zone.gina_work
  - platform: template
    sensors:
      front_door_sensor:
        value_template: '{% if is_state("binary_sensor.aeotec_zw112_door_window_sensor_6", "on") %}open{% else %}closed{% endif %}'
        friendly_name: 'Front Door Sensor'
  - platform: template
    sensors:
      front_door_sensor_batt:
        value_template: "{{ states.binary_sensor.aeotec_zw112_door_window_sensor_6.attributes.battery_level }}"
        friendly_name: 'Front Door Sensor'
        unit_of_measurement: '%'

# Track the sun
sun:

switch:
  - platform: command_line
    switches:
      frontdoor_kevo:
        command_on: 'python2.7 /home/homeassistant/.homeassistant/kevo/lock-liberty.py'
        command_off: 'python2.7 /home/homeassistant/.homeassistant/kevo/unlock-liberty.py'
        command_state: 'python2.7 /home/homeassistant/.homeassistant/kevo/status-liberty.py'
        value_template: '{{ value == "Locked" }}'
  - platform: command_line
    switches:
      sleepytime_tasker:
        command_on: 'python3 /home/homeassistant/.homeassistant/python_scripts/sleepytime_tasker.py'

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

wemo:

zwave:
  usb_path: /dev/ttyACM0
#  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
#  device_config: !include zwave_device_config.yaml
  new_entity_ids: true


####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
group: !include groups.yaml
automation: !include automations.yaml

# Single Files

logger: !include logger/logger.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
shell_command: !include shell_commands.yaml
#zwave: !include zwave_device_config.yaml

# Merge List
# will return the content of a directory as a list
# with each file content being an entry in the list
alert: !include_dir_merge_list alert

script:
  backup_ha:
    sequence:
#      - service: shell_command.mount_dir
      - service: shell_command.backup_folder
      - service: shell_command.backup_configuration
      - service: notify.html5
        data:
          title: "Backing Up HA Configs"
          message: 'Backup started'
          target: "bills_6p"
          data:
            tag: 'backup_script'
  bed_colorloop:
    sequence:
      - service: light.turn_on
        data:
          entity_id: group.bed_lights
          effect: colorloop
          brightness: 250
          transition: 5
  bedtime_music:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.bedroom
          source: 'River Flows In You - Original'
  panic1:
    sequence:
      - service: light.turn_on
        entity_id:
          - group.bed_lights
        data:
          brightness: 250
          xy_color: [ 0.329, 0.35 ]
      - service: light.turn_on
        data:
          entity_id: group.bed_lights
          flash: short
          brightness: 250
          xy_color: [ 0.704, 0.296 ]
      - delay:
          seconds: 3
      - service: script.panic2
  panic2:
    sequence:
      - service: light.turn_on
        data:
          entity_id: group.bed_lights
          flash: short
          brightness: 250
          xy_color: [ 0.704, 0.296 ]
      - delay:
          seconds: 3
      - service: script.panic1
  pull_from_github:
    sequence:
      - service: shell_command.git_pull
      - service: homeassistant.restart
  sonos_tts:
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.sonos_unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: tts.voicerss_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "{{ delay }}"
      - service: media_player.sonos_restore
        data_template:
          entity_id: "{{ sonos_entity }}"
  zanzito_send_notification:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zanzito/{{ dest_id }}/notification'
          payload: '{{ message }}'
          qos: 1
          retain: 0

# Dir List
zone: !include_dir_list zones


####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
# Enables configuration UI
config:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Discover some devices automatically
discovery:
# Enables the frontend
frontend:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true
recorder:
  purge_days: 3




