####################################################
#                                                  #
#               HA 2 General Confi                 #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_path
  ssl_key: !secret ssl_key
  base_url: !secret http_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

####################################################
#                                                  #
#               Components                         #
#                                                  #
####################################################

alarm_control_panel:
  platform: manual
  name: Alarm
  pending_time: 0
  trigger_time: 600
  disarm_after_trigger: false

climate:
  platform: nest

ifttt:
  key: !secret ifttt_secret

mqtt:
  broker: 192.168.0.25
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  binary_sensors:
    monitored_conditions:
      - 'online'
      - 'fan'
      - 'is_using_emergency_heat'
      - 'is_locked'
      - 'has_leaf'

# Weather Prediction
sensor:
  platform: yr

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

wemo:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config



####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
group: !include groups.yaml
automation: !include automations.yaml

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
# Enables configuration UI
config:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Discover some devices automatically
discovery:
# Enables the frontend
frontend:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true
recorder:
  purge_days: 3




